### ISSUE TITLE
Missing ResNeXt50 and mfccNet

### ISSUE THREAD

**Issue by Nickick-ICRS** [skeletonNN/CFN-SR#2]
Hi,

I'm unable to test this network, as there's no checkpoints folder with ResNeXt50 and mfccNet within it. I would happily download the model separately, but I don't know to do so. The specific error is a FileNotFoundError when trying to load ResNeXt50. I expect the same will happen for mfccNet once ResNeXt50 exists:

```
Traceback (most recent call last):
  File "main_msaf.py", line 163, in <module>
    video_model_checkpoint = torch.load(video_model_path) if use_cuda else \
  File "/home/nickick/phd/CFN-SR/env/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/nickick/phd/CFN-SR/env/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/nickick/phd/CFN-SR/env/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/resnext50/fold_1_resnext50_best.pth'
```

Could you update the repository to include those two models, or include links on where to find them, or instructions on the steps taken to train them if that approach was taken?

Thanks,
Nick

**Comment by Nickick-ICRS** [comment]
My mistake, missed the download checkpoints bash script.
